### ISSUE TITLE
Suggestion: Specify in readme's build instructions for the example app that conan v2 is not supported

### ISSUE THREAD

**Issue by pineapplemachine** [hnOsmium0001/imgui-command-palette#7]
I was referring to this repository to implement a similar UI feature myself, and wanted to build the example app to refer to its behavior. I ended up on a whole adventure trying to build the example app, which was finally resolved by giving up trying to build with conan v2 and installing conan 1.61.0 instead. For anyone else who ends up wanting to build the example app who was not previously familiar with conan, it may save them quite a bit of time if this was stated in the build instructions.

**Comment by hnOsmium0001** [comment]
Thank you for reminding me!

After I wrote this project I really never paid attention to the example build system. Apologizes for using up so much of your time.

I have just pushed a few commits that replaced the old conan v1 buildsystem with two options, one CMake+vcpkg based, one system deps based. The README is also updated with more detailed instructions.

I no longer have the necessary knowledge to get conan2 to work -- after the v2 migration, I spent quite a bit of time on other projects but eventually gave up on using conan at all, and switched pretty much everything to vcpkg. If you want me to include a conan option for building the example app, sadly you will have to PR it -- I don't have the time nor energy to learn conan2 at all.
