### ISSUE TITLE
Does not build, calculation of width deprecated.

### ISSUE THREAD

**Issue by AlexLao512** [hnOsmium0001/imgui-command-palette#8]
To compile in the latest build of ImGui (or anything past about 2021), line 535 of imcmd_command_palette.cpp has to be changed to `float width = ImGui::GetWindowContentRegionMax().x - ImGui::GetWindowContentRegionMin().x;`

**Comment by hnOsmium0001** [comment]
This is definitely my bad for not using `IMGUI_DISABLE_OBSOLETE_FUNCTIONS`. Thanks for reporting it!

I generally use vcpkg in my dev environment, and defining an extra flag is hoops that I prefer not to jump through. Although just a side note: the `builtin_baseline` in `examples/app-vcpkg/vcpkg.json` is the version I test with in my dev environment, so anybody ever have trouble building try using that.
